-- PostgreSQL / H2 (MODE=PostgreSQL) 両対応の DDL。
-- BIGSERIAL は PG 固有のため、SQL 標準の GENERATED BY DEFAULT AS IDENTITY を採用
-- （PG 10+ / H2 2.x ともにサポート）。E2E は WildFly + H2 ファイル DB で本ファイルを
-- Flyway maven plugin で migrate する。IT (JpaTestSupport.bootstrapH2) も同じファイルを
-- classpath から直接 execute するため、テスト用に別 V1 を持たない。
CREATE TABLE task (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         VARCHAR(100) NOT NULL,
  status        VARCHAR(4)   NOT NULL,
  created_at    TIMESTAMP    NOT NULL,
  completed_at  TIMESTAMP,
  CONSTRAINT chk_task_status CHECK (status IN ('TODO','DONE')),
  CONSTRAINT chk_task_completed CHECK (
    (status = 'TODO' AND completed_at IS NULL) OR
    (status = 'DONE' AND completed_at IS NOT NULL)
  )
);

CREATE INDEX idx_task_created_at ON task (created_at);
