-- PostgreSQL / H2 (MODE=PostgreSQL) 両対応の DDL。
-- BIGSERIAL は PG 固有のため、SQL 標準の GENERATED BY DEFAULT AS IDENTITY を採用
-- （PG 10+ / H2 2.x ともにサポート）。E2E は WildFly + H2 ファイル DB で本ファイルを
-- Flyway maven plugin で migrate する。IT (JpaTestSupport.bootstrapH2) も同じファイルを
-- classpath から直接 execute するため、テスト用に別 V1 を持たない（CHECK 制約も H2 で
-- 解釈可能）。
CREATE TABLE leave_request (
  id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_emp_num   VARCHAR(20)  NOT NULL,
  applicant_name      VARCHAR(100) NOT NULL,
  applicant_org_id    VARCHAR(20)  NOT NULL,
  applicant_org_name  VARCHAR(200) NOT NULL,
  leave_type          VARCHAR(20)  NOT NULL,
  start_date          DATE         NOT NULL,
  end_date            DATE         NOT NULL,
  reason              VARCHAR(500) NOT NULL,
  status              VARCHAR(20)  NOT NULL,
  applied_at          TIMESTAMP    NOT NULL,
  judge_emp_num       VARCHAR(20),
  judge_name          VARCHAR(100),
  judged_at           TIMESTAMP,
  judge_comment       VARCHAR(500),
  CONSTRAINT chk_leave_period CHECK (start_date <= end_date),
  CONSTRAINT chk_leave_judge_complete CHECK (
    (status = 'PENDING' AND judge_emp_num IS NULL AND judged_at IS NULL) OR
    (status IN ('APPROVED','REJECTED') AND judge_emp_num IS NOT NULL AND judged_at IS NOT NULL)
  )
);

CREATE INDEX idx_leave_request_applicant ON leave_request (applicant_emp_num);
CREATE INDEX idx_leave_request_org_status ON leave_request (applicant_org_id, status);
